[Feature: #162727562] Tag articles
andela/pippin-ah-backend pull request #64
Opened 2019-01-23 19:21 UTC by habibaudu

#### What does this PR do?
- Tag Articles
#### Description of Task to be completed?
- [x] Change tags column data type in the article models to  Array
- [x] Tag Articles
#### How should this be manually tested?
- Fire up postman
- Url: [Here](http://localhost:4000/api/v1/articles/tag)
- Enter `tags` and `title`
- Click Send

#### What are the relevant pivotal tracker stories?
[#162727562](https://www.pivotaltracker.com/story/show/162727562)

2019-01-23 20:16 UTC, oreoluwade requested changes

2019-01-23 20:16 UTC, oaboluwarin commented on models/article.js
> +      type: DataTypes.ARRAY(DataTypes.TEXT)
Replace `DataTypes.TEXT` with `DataTypes.STRING`

2019-01-23 20:16 UTC, oaboluwarin commented on migrations/009-create-articles-update-tag.js
> +      ${Sequelize.ARRAY(Sequelize.TEXT)})`
Replace `Sequelize.TEXT` with `Sequelize.STRING`

2019-01-23 20:20 UTC, oaboluwarin commented
- Remove the space that is line 68 in the article controllers file.

- The coverage has dropped. Found that line 54 is not tested. This means that there's no test for when tags have already been added before and a new tag is added. So you need to add one more test spec.

2019-01-24 01:24 UTC, habibaudu commented on models/article.js
> +      type: DataTypes.ARRAY(DataTypes.TEXT)
ok

2019-01-24 01:31 UTC, habibaudu commented
> * Remove the space that is line 68 in the article controllers file.
> * The coverage has dropped. Found that line 54 is not tested. This means that there's no test for when tags have already been added before and a new tag is added. So you need to add one more test spec.

ok

2019-01-24 06:29 UTC, oreoluwade approved these changes

2019-01-24 06:29 UTC, merged